import type { GetStaticPaths, NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.scss'
import { GetStaticProps } from 'next'
import getArticle, {PageProps} from '../../utils/get_article'
import { getPaths } from '../../utils/get_paths'

type PathParams = {
  id: string,
}

const Home = (props: PageProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ぶろぐ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{props.title}</p>
        <p>{props.article}</p>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home

export const getStaticPaths: GetStaticPaths = async() => {
  const getpaths = await getPaths();

  const paths = getpaths.map(id => ({params:{id: id || "404"}}));

  return{
    paths,
    fallback: true
  }
}

export const getStaticProps: GetStaticProps = async(context) => {
  const { id } = context.params as PathParams;
  const getprops = await getArticle(id);
  return getprops.title?({
    props:{
      title: getprops.title,
      article: getprops.article
    },
    revalidate: 300,
  }):{
    redirect:{
      destination: "/404",
      permanent: false
    }
  }
}
